In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
tips = sns.load_dataset('tips')

In [3]:
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
5         25.29  4.71    Male     No   Sun  Dinner     4
6          8.77  2.00    Male     No   Sun  Dinner     2
7         26.88  3.12    Male     No   Sun  Dinner     4
8         15.04  1.96    Male     No   Sun  Dinner     2
9         14.78  3.23    Male     No   Sun  Dinner     2
10        10.27  1.71    Male     No   Sun  Dinner     2
11        35.26  5.00  Female     No   Sun  Dinner     4
12        15.42  1.57    Male     No   Sun  Dinner     2
13        18.43  3.00    Male     No   Sun  Dinner     4
14        14.83  3.02  Female     No   Sun  Dinner     2
15        21.58  3.92    Male     No   Sun  Dinner     2
16        10.33  1.67  Female     No   Sun  Dinner     3
17        16.29  3.71    Male     No   Sun  Dinner     3
18        16.97  3.50  Female     No   Sun  Dinner     3
19        20.65  3.35    Male     No   Sat  Dinner     3
20        17.92  4.08    Male     No   Sat  Dinner     2
21        20.29  2.75  Female     No   Sat  Dinner     2
22        15.77  2.23  Female     No   Sat  Dinner     2
23        39.42  7.58    Male     No   Sat  Dinner     4
24        19.82  3.18    Male     No   Sat  Dinner     2
25        17.81  2.34    Male     No   Sat  Dinner     4
26        13.37  2.00    Male     No   Sat  Dinner     2
27        12.69  2.00    Male     No   Sat  Dinner     2
28        21.70  4.30    Male     No   Sat  Dinner     2
29        19.65  3.00  Female     No   Sat  Dinner     2
..          ...   ...     ...    ...   ...     ...   ...
214       28.17  6.50  Female    Yes   Sat  Dinner     3
215       12.90  1.10  Female    Yes   Sat  Dinner     2
216       28.15  3.00    Male    Yes   Sat  Dinner     5
217       11.59  1.50    Male    Yes   Sat  Dinner     2
218        7.74  1.44    Male    Yes   Sat  Dinner     2
219       30.14  3.09  Female    Yes   Sat  Dinner     4
220       12.16  2.20    Male    Yes   Fri   Lunch     2
221       13.42  3.48  Female    Yes   Fri   Lunch     2
222        8.58  1.92    Male    Yes   Fri   Lunch     1
223       15.98  3.00  Female     No   Fri   Lunch     3
224       13.42  1.58    Male    Yes   Fri   Lunch     2
225       16.27  2.50  Female    Yes   Fri   Lunch     2
226       10.09  2.00  Female    Yes   Fri   Lunch     2
227       20.45  3.00    Male     No   Sat  Dinner     4
228       13.28  2.72    Male     No   Sat  Dinner     2
229       22.12  2.88  Female    Yes   Sat  Dinner     2
230       24.01  2.00    Male    Yes   Sat  Dinner     4
231       15.69  3.00    Male    Yes   Sat  Dinner     3
232       11.61  3.39    Male     No   Sat  Dinner     2
233       10.77  1.47    Male     No   Sat  Dinner     2
234       15.53  3.00    Male    Yes   Sat  Dinner     2
235       10.07  1.25    Male     No   Sat  Dinner     2
236       12.60  1.00    Male    Yes   Sat  Dinner     2
237       32.83  1.17    Male    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [5]:
## key값으로 접근
tips['day']

0       Sun
1       Sun
2       Sun
3       Sun
4       Sun
5       Sun
6       Sun
7       Sun
8       Sun
9       Sun
10      Sun
11      Sun
12      Sun
13      Sun
14      Sun
15      Sun
16      Sun
17      Sun
18      Sun
19      Sat
20      Sat
21      Sat
22      Sat
23      Sat
24      Sat
25      Sat
26      Sat
27      Sat
28      Sat
29      Sat
       ...
214     Sat
215     Sat
216     Sat
217     Sat
218     Sat
219     Sat
220     Fri
221     Fri
222     Fri
223     Fri
224     Fri
225     Fri
226     Fri
227     Sat
228     Sat
229     Sat
230     Sat
231     Sat
232     Sat
233     Sat
234     Sat
235     Sat
236     Sat
237     Sat
238     Sat
239     Sat
240     Sat
241     Sat
242     Sat
243    Thur
Name: day, Length: 244, dtype: category
Categories (4, object): [Thur, Fri, Sat, Sun]

In [7]:
##attribute로 접근
tips.smoker

0       No
1       No
2       No
3       No
4       No
5       No
6       No
7       No
8       No
9       No
10      No
11      No
12      No
13      No
14      No
15      No
16      No
17      No
18      No
19      No
20      No
21      No
22      No
23      No
24      No
25      No
26      No
27      No
28      No
29      No
      ...
214    Yes
215    Yes
216    Yes
217    Yes
218    Yes
219    Yes
220    Yes
221    Yes
222    Yes
223     No
224    Yes
225    Yes
226    Yes
227     No
228     No
229    Yes
230    Yes
231    Yes
232     No
233     No
234    Yes
235     No
236    Yes
237    Yes
238     No
239     No
240    Yes
241    Yes
242     No
243     No
Name: smoker, Length: 244, dtype: category
Categories (2, object): [Yes, No]

In [8]:
tips.size

1708

In [9]:
tips['size']

0      2
1      3
2      3
3      2
4      4
5      4
6      2
7      4
8      2
9      2
10     2
11     4
12     2
13     4
14     2
15     2
16     3
17     3
18     3
19     3
20     2
21     2
22     2
23     4
24     2
25     4
26     2
27     2
28     2
29     2
      ..
214    3
215    2
216    5
217    2
218    2
219    4
220    2
221    2
222    1
223    3
224    2
225    2
226    2
227    4
228    2
229    2
230    4
231    3
232    2
233    2
234    2
235    2
236    2
237    2
238    3
239    3
240    2
241    2
242    2
243    2
Name: size, Length: 244, dtype: int64

In [11]:
tips.iloc[0]

total_bill     16.99
tip             1.01
sex           Female
smoker            No
day              Sun
time          Dinner
size               2
Name: 0, dtype: object

In [13]:
tips.loc[0]

total_bill     16.99
tip             1.01
sex           Female
smoker            No
day              Sun
time          Dinner
size               2
Name: 0, dtype: object

일반적으로 사용하는 거의 모든 툴은 2차원 직사각형 형태로 가정을 해놨음

fancy indexing in pandas

In [16]:
tips[['day','time']]

      day    time
0     Sun  Dinner
1     Sun  Dinner
2     Sun  Dinner
3     Sun  Dinner
4     Sun  Dinner
5     Sun  Dinner
6     Sun  Dinner
7     Sun  Dinner
8     Sun  Dinner
9     Sun  Dinner
10    Sun  Dinner
11    Sun  Dinner
12    Sun  Dinner
13    Sun  Dinner
14    Sun  Dinner
15    Sun  Dinner
16    Sun  Dinner
17    Sun  Dinner
18    Sun  Dinner
19    Sat  Dinner
20    Sat  Dinner
21    Sat  Dinner
22    Sat  Dinner
23    Sat  Dinner
24    Sat  Dinner
25    Sat  Dinner
26    Sat  Dinner
27    Sat  Dinner
28    Sat  Dinner
29    Sat  Dinner
..    ...     ...
214   Sat  Dinner
215   Sat  Dinner
216   Sat  Dinner
217   Sat  Dinner
218   Sat  Dinner
219   Sat  Dinner
220   Fri   Lunch
221   Fri   Lunch
222   Fri   Lunch
223   Fri   Lunch
224   Fri   Lunch
225   Fri   Lunch
226   Fri   Lunch
227   Sat  Dinner
228   Sat  Dinner
229   Sat  Dinner
230   Sat  Dinner
231   Sat  Dinner
232   Sat  Dinner
233   Sat  Dinner
234   Sat  Dinner
235   Sat  Dinner
236   Sat  Dinner
237   Sat  Dinner
238   Sat  Dinner
239   Sat  Dinner
240   Sat  Dinner
241   Sat  Dinner
242   Sat  Dinner
243  Thur  Dinner

[244 rows x 2 columns]